### ISSUE TITLE
SQLCommand ends in IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Gertray13** [six42/jdbcslim#39]
When using SQLCommand we sometimes get an `IndexOutOfBoundsException`.

```
!|SQLCommand|Database|select bla from test where bla in('This', 'That')|sort|
|bla?<|
|This |
|That |
```

```
__EXCEPTION__:java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) [n/a]
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) [n/a]
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) [n/a]
at java.base/java.util.Objects.checkIndex(Objects.java:372) [rt.jar]
at java.base/java.util.ArrayList.get(ArrayList.java:458) [rt.jar]
at six42.fitnesse.jdbcslim.StringListComparator.compare(StringListComparator.java:50) [jdbcslim.jar]
at six42.fitnesse.jdbcslim.SheetFixture.compareTableWithSort(SheetFixture.java:373) [jdbcslim.jar]
at six42.fitnesse.jdbcslim.SheetFixture.processComandOnceAndCompareToExpected(SheetFixture.java:92) [jdbcslim.jar]
at six42.fitnesse.jdbcslim.SheetFixture.doTable(SheetFixture.java:58) [jdbcslim.jar]
at six42.fitnesse.jdbcslim.SheetCommandBase.doTable(SheetCommandBase.java:68) [jdbcslim.jar]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [n/a]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [n/a]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [n/a]
at java.base/java.lang.reflect.Method.invoke(Method.java:567) [rt.jar]
```

![image](https://user-images.githubusercontent.com/58523899/79779755-25e07e80-833b-11ea-802d-07daf8261900.png)

How come I sometimes get this error and most of the time it does not give this error?

**Comment by Unforgettable631** [comment]
When this issue occurs for you, are you sure the resultset (output of the query) is **not** empty?
I believe when the output is empty you will get that error.

If so you can try to extend `public int compare` in [StringListComparator.java](https://github.com/six42/jdbcslim/blob/db093b3c3eec330bf8dd104caee08cc6bfbc51f7/src/main/java/six42/fitnesse/jdbcslim/StringListComparator.java#L28) with something like 
```
for (int i = 0; i < _SortKeys1.size(); i++) {
     if (!a1.isEmpty() && !a2.isEmpty() {
     .....
     } else if....
```

Otherwise you can also write your test differently (with `run`) and explicitly check on a rowcount.
If above is helping more people I can also create a PR for that. Or maybe @six42 has a better approach for your isse?

**Comment by Gertray13** [comment]
@Unforgettable631, you are right. `IndexOutOfBoundsException` only occurs when the query is empty at that moment. I would like to see that the expected values are missing when the query gives an empty result.

**Comment by Unforgettable631** [comment]
Something like this?

```
!|SQLCommand|TestDatabase|select ID,Name from TestData where Name in('notThere', 'unknown')|SORT|
|ID?|NAME?>|
|1|notThere|
|2|unknown|

!|SQLCommand|TestDatabase|select ID,Name from TestData where Name in('notThere', 'unknown')|SORT|
|ID?|NAME?>|
|=~/\A\z/|=~/\A\z/|
```

**Before:**
![image](https://user-images.githubusercontent.com/26714288/79956475-7dd4cd80-8480-11ea-828f-6d08198a3cce.png)

![image](https://user-images.githubusercontent.com/26714288/79956560-96dd7e80-8480-11ea-8d82-1b106d1292c5.png)

**After adjustment:**
![image](https://user-images.githubusercontent.com/26714288/79956009-d8215e80-847f-11ea-9b4f-2466b3cd8ca7.png)

**Comment by six42** [comment]
Thanks @Gertray13 for reporting this and thanks @Unforgettable631 for finding a soution and writing a test case to confirm it.

**Comment by Unforgettable631** [comment]
@six42, no problem. Your fix is more robust I think. Do you have any intentions to release the latest version?
